name: notify_movie_upcoming

on:
    push:
        branches: [ develop ]
jobs:
    notify_job:
        runs-on: ubuntu-18.04
        name: Notify
        steps:
            - name: Build
            uses: actions/Apartment@develop
            run: ls
