version: '3' # composeファイルのバーション指定
services:
  app: # service名
    build: . # ビルドに使用するDockerfileがあるディレクトリ指定
    tty: true # コンテナの起動永続化
    ports:
      - 1323:1323
    volumes:
      - .:/go/src/work # マウントディレクトリ指定
