gmail:
    from: udmr.orrr1414@gmail.com
    to: udmr.orrr1414@gmail.com
    password: Vino4628
    smtp: smtp.gmail.com
    port: 587
movieUpcoming:
    fromName: 今月の映画情報のお知らせ
    subject: 【映画情報のお知らせ】今月の公開予定映画一覧


